@HostAddress = http://localhost:5195

GET {{HostAddress}}/api/student/all
Accept: application/json

###

GET {{HostAddress}}/api/student/list?pageNo=1&pageSize=5
Accept: application/json

###

POST {{HostAddress}}/api/student
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

###

GET {{HostAddress}}/api/student/1
Accept: application/json

###

PUT {{HostAddress}}/api/student/1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john.updated@example.com"
}

###

DELETE {{HostAddress}}/api/student/1
Accept: application/json
